name: Workflow to generate ascii

on: push

jobs:
    generate_ascii:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: list files
              run: ls -ltra
            - name: Add Permissions and execute script
              run: |
                chmod +x generate_ascii.sh
                ./generate_ascii.sh