name: Workflow to generate ascii

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: install cowsay
              run: sudo apt-get install cowsay -y
            - name: generate dragon file
              run: cowsay -f dragon "Run for cover, I am a DRAGON...RAMR" >> dragon.txt
            - name: upload dragon file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
            - name: download dragon file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file
            - name: test if file downloaded successfully
              run: grep -i "dragon" dragon.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        needs: test_job_2
        steps:
            - name: download dragon file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file
            - name: display dragon file content
              run: cat dragon.txt